#!/bin/bash
chsh -s $(which zsh)
ln -vfs $PWD/zshrc $HOME/.zshrc
ln -vfs $PWD/tmux.conf $HOME/.tmux.conf
if [ $(uname) == "Linux" ]; then 
	ln -vfs $PWD/Xresources $HOME/.Xresources
	ln -vfs $PWD/xinitrc $HOME/.xinitrc
	[[ -z $(command -v compton >/dev/null 2>&1) ]] && ln -vfs $PWD/compton.conf $HOME/.compton.conf
fi
